# SPDX-License-Identifier: GPL-3.0-or-later
"""Collect upstream copyright/license comments for binary distributions."""
from pathlib import Path
import argparse, re
ROOT=Path(__file__).resolve().parent

def render():
    notices={}
    for path in sorted((ROOT/'vendor').rglob('*.java'),key=lambda p:p.as_posix()):
        for comment in re.findall(r'/\*[\s\S]*?\*/|//[^\n]*',path.read_text(encoding='utf-8')):
            if re.search(r'copyright|licen[sc]e|public domain|all rights reserved',comment,re.I):
                notices.setdefault(comment,[]).append(path.relative_to(ROOT).as_posix())
    parts=['Upstream notices retained from the vendored Java sources.\n'
           'Generated by notices.py. Full licenses: LICENSE, licenses/, vendor/*/LICENSE.\n'
           'File lists identify where each original notice appears.\n']
    for notice,paths in notices.items():
        parts.append('\n'+'='*72+'\n'+'\n'.join(paths)+'\n\n'+notice+'\n')
    return ''.join(parts)

def verify():
    if (ROOT/'NOTICE.txt').read_text(encoding='utf-8')!=render():
        raise ValueError('NOTICE.txt is stale; run python notices.py')

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true')
    if parser.parse_args().check: verify();print('Verified upstream notices')
    else: (ROOT/'NOTICE.txt').write_text(render(),encoding='utf-8',newline='\n');print('Wrote NOTICE.txt')
